### ISSUE TITLE
I installed and nothing shows on my Homekit

### ISSUE THREAD

**Issue by Tesla-P100FX** [mantorok1/homebridge-omnilink-platform#1]
**Describe Your Problem:**

So today i use HomeSeer 4 pointed at my OmniPro II.  Then HomeBridge HomeSeer install.  That all works.    I installed this this morning.  I know my Keys, and IP address.  So it should show up,  However nothing shows up in the logs and nothing happens in Homekit on my phone.  I didn't know can i have HomeSeer and your platform pointed at my OmniPro at the same time?   

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by mantorok1** [comment]
Hi, so just to confirm you've had the Homeseer4 plugin working fine for some time and have recently installed my plugin but it's not working - nothing in the logs and no accessories added to HomeKit.
Could you please paste a copy of the OmniLinkPlatform config (with sensitive info removed) from the config.json file. Also, can you set Homebridge into DEBUG mode and restart. This will show more detailed logs. If there's anything in those logs that relate to my plugin could you also paste that too.

**Comment by mantorok1** [comment]
@Tesla-P100FX, can you also check the Homebridge logs to see if the plugin is loaded. It should looks something like this:
`[10/5/2020, 3:39:41 PM] Loaded plugin: homebridge-omnilink-platform@1.1.1
[10/5/2020, 3:39:41 PM] Registering platform 'homebridge-omnilink-platform.OmniLinkPlatform'`
And also if the plugin is initialized:
`[10/5/2020, 3:39:43 PM] [Omni] Initializing OmniLinkPlatform platform...`

**Comment by mantorok1** [comment]
@Tesla-P100FX, haven't heard from you since you raised this issue. Did you manage to get the plugin working?

If I don't hear from you in the next few days I'll assume everything is ok and I'll close this issue.

Regards

**Comment by Tesla-P100FX** [comment]
I uninstalled it then was out of town,   have you updated it since?

**Comment by mantorok1** [comment]
Hi @Tesla-P100FX, there's been no further updates to the plugin. When you get a chance could you re-install the plugin and provide the Homebridge logs as requested above. With those logs I'll have a better idea what is going on. Thanks

**Comment by mantorok1** [comment]
Hey @Tesla-P100FX, any chance you can get the config and logs to me soon? I've got some spare time this weekend and was planning to do some work on the plugin. It would be good if I can resolve your issue as part of that. I'm not sure when I'll get time to work on it again after this weekend.

**Comment by mantorok1** [comment]
I'm closing this issue as the requested information has not been provided. If you wish me to investigate this further then raise another issue and ensure you provide the following information:

- Homebridge version
- Plugin version
- Copy of the config.json file (with sensitive information removed)
- Copy of Homebridge logs (with Homebridge in DEBUG mode)
