### ISSUE TITLE
no dimming functionality

### ISSUE THREAD

**Issue by usergregory** [mantorok1/homebridge-omnilink-platform#11]
**Describe Your Problem:**
i've installed the plugin and configured all the switches but none of them have dimming capability.  I have them set as lights and not switches.  What am I doing wrong

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.45
* **Homebridge Version**:  hoobs latest version 4.0.71
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**: hoobs on raspberry pi

**Comment by usergregory** [comment]
figured it out

**Comment by bwolsey** [comment]
Hello.  I installed Hoobs and the Omnilink plugin last weekend and everything except dimming working great.  I'm new to Hoobs, but somewhat computer savvy and familiar with Dealer PC Access (and have access to the back end of my Omnilink system). I would appreciate if someone could point me in a helpful direction.  

Omnilink Platform Version: 1.5.4
Homebridge Version: Hoobs latest version 4.2.1
Controller: Omni LTe (3.14A)
Node.js Version: Not sure how to obtain this.
NPM Version: Not sure how to obtain this.

**Comment by mantorok1** [comment]
Hi @bwolsey, you haven't provided your config but one thing to check is to ensure you have the Omni units (i.e. your lights) as "lightbulbs" and not "switches" in the config

**Comment by bwolsey** [comment]
Hello @mantorok1.  You nailed it.  I was reading more about the various settings and figured out that if I was statefull (by including the address vs just letting it scan and include everything), it would fix that.  I just did that and it seems to have worked.  THANK YOU for making such a GREAT Bridge.
