### ISSUE TITLE
TCP Connection Problem

### ISSUE THREAD

**Issue by Riveloper** [mantorok1/homebridge-omnilink-platform#12]
**Describe Your Problem:**

Most likely this is not a problem with the plug-in, or anything you can control.

I tried for a week at my family to connect to their OmniPro II using this plug-in. Ping successfully to IP associated with OmniPro. Confirmed port and keys are correct.

Under status the only message returned is TCP connection failed. 

I am going to visiting them again before Christmas and really want to solve this. If there is any help you can provide or if this is a bug, I can offer any details you need to identify it.

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by mantorok1** [comment]
Hi @Riveloper, sounds like a network connectivity issue. Are you able to provide the full log message(s) from Homebridge from when the plugin starts?

A few things to try:
- Did you ping the IP address of the Omni controller from the the device that is running Homebridge? What is the device?
- Are you able to use the SnapLink (or Myro:Home) app on an iPhone connected to the local network with the IP of the Omni?

**Comment by Riveloper** [comment]
I won't be able to provide the log since I am in another state than my family. But the only message repeating every 60 seconds was "TCP/IP connection failed."

I was able to ping the OmniPro from the iMac running Homebridge and did get regular responses.

I did not use Snaplink as I am not familiar but will call my father and try to walk him through using it.

----

I do want to mention they are using a Mesh Network by erro. I do not believe this is the problem but have little experience with mesh networks.

I did find online that the Ethernet cable and router could be too fast for the OmniPro and has forced some Homeseer users to buy and older switch to place between the OmniPro and the LAN. Since I can ping the device I ignored this as a possible problem. 

----

Thank you for your assistance. I hope we can determine if this is a problem with the network or maybe even provide insight for you to improve the plug-in.

**Comment by mantorok1** [comment]
Was that the actual error message you saw? Or was it something like:
```
Connection to controller failed: TCP/IP connection failed.
```
If you do visit your family again soon your can try putting Homebridge into DEBUG mode in the settings which will produce more detailed logs.

Another thing worth trying to see if the Mac is able to connect to the Omni controller's IP and port is to use the following command from the terminal:
```
nc -vz 192.168.1.210 4369
```
Just replace the IP address with the appropriate one for your family's controller. 4369 is the default port for an Omni. If all is well you should see something like:
```
Connection to 192.168.1.210 port 4369 [tcp/epmd] succeeded!
```

**Comment by Riveloper** [comment]
Yes that is the error. 

I was able to ping the OmniPro from the Mac terminal but I will try the command you mentioned on my next visit. 

I did find that Homeseer sets a delay wait time for each command to 3000ms before expecting a response. As the OmniPro can only handle 10mbs but most modern connections are much faster. Perhaps this is relevant.

Thanks again. I will be there during Christmas.

**Comment by mantorok1** [comment]
Ping will just check that the target host is reachable. The nc command will try to establish a TCP connection to the host and port so its more like what the plugin is trying to do.

I don't know anything about Homeseer but it could be interfering with the connectivity I guess.

Good luck and let me know how it goes

**Comment by mantorok1** [comment]
Hi @Riveloper, did you manage get the plugin working?

**Comment by mantorok1** [comment]
Stale
