### ISSUE TITLE
Hifi2 Audio Zones and Sources

### ISSUE THREAD

**Issue by dfrank811** [mantorok1/homebridge-omnilink-platform#15]
Do you have any plans to implement the audio zones and sources?  I have the hifi2 panel that connects to my OMNI Pro panel.  It provides distributed audio to multiple rooms.  I believe that the Hifi2 panel shows up as a feature.  Each set of speakers show up as zones.
It would be very handy to be able to manage these audio zones through HomeKit.

Great job on this plug-in.  It has been a huge help to me and works great.

**Comment by mantorok1** [comment]
Hi @dfrank811,
Glad to hear the plugin is working well for you.

I'm not familiar with how the Omni audio zones & sources work. If you could describe their functionality and what HomeKit control you're hoping to achieve I can see what I can do.
Also, could you supply your Homebridge logs that show what zones, units, etc the plugin finds when it starts.

**Comment by mantorok1** [comment]
I've had a look at the Omnilink API doc and from what I can make out the audio sources are just a list of sources to supply audio to the various audio zones (I'm guessing it would be things like radio or CD player). Audio zones are a speaker (or set of speakers) where you can control the power (on/off), volume level, muting (on/off) and audio source. Is that correct?

On the Homebridge/HomeKit side there is a "Speaker" service that allows you to control the power, volume & muting but it doesn't support selecting an audio source. So what I could do is create one "Speaker" accessory for each audio zone.

I'm not sure how to solve the selection of the audio source though. I could create switches for each audio source but I'd need to create as set of switches for each audio zone so you may end up with a lot of switches (depending on how many sources & zones you have).  If you only tend to have the one source selected for ALL audio zones then only one set of switches would be necessary.

**Comment by dfrank811** [comment]
Yeah, that sounds right.  I currently have 4 speaker zones and 4 sources.
Most of my sources are connected to Bluetooth receivers.  That way when I
go into a room it normally connects to my phone and I can listen.  The nice
part of the system is that you could have all the speakers playing from the
same source or different sources.  I have one source connected to my tv
audio so if there is a game on I can play that on all of the speaker zones.

The HiFi2 panels came in 2 forms.  A 4 zone, 4 source one and an 8 zone, 8
source one.

If it would help I could send you some screenshots of how it looks in the
PC Access app.

**Comment by mantorok1** [comment]
Hi @dfrank811, I don't think I need the screenshots at this stage.

I have just published a new version of the plugin (1.5.3) which will attempt to discover audio sources & zones. It won't create any HomeKit accessories yet. Could you please install it & restart. Then see if its able to find your audio sources & zones and copy and paste what it finds here. For me the Homebridge logs look like this:
```
[1/27/2022, 9:04:12 AM] [Omni] Audio Sources found: 0
[1/27/2022, 9:04:12 AM] [Omni] Audio Zones found: 0
```
Could you also see if the plugin is capturing the event notifications from the Omni Controller for the Audio Zones. To do this you'll need to turn on the "Show Omni event notifications in the log" in the plugin's settings & restart. To test you need to change various properties of the audio zones (ie. power, source, volume & mute) using the same method you currently do. These changes should be reported in the Homebridge logs.

If all that works successfully then I can move onto creating HomeKit accessories though I'm still not sure how to best handle the source selection.

**Comment by dfrank811** [comment]
Yeah, it looks like it is finding them.

[image: image.png]

**Comment by mantorok1** [comment]
Thanks @dfrank811,

Did you also confirm that the audio zone event notifications were working?

**Comment by dfrank811** [comment]
Sorry it took me so long, but I just tested it and I am not seeing anything
in the logs when I turn the zones on and off.  I will try to test it a
little more tonight.

**Comment by mantorok1** [comment]
Thanks for taking the time to test this. Do you see any other types of notifications in the logs like your motion sensors (ie. zones)? They should look something like this:
```
[2/8/2022, 7:57:27 AM] [Omni] Zone 12 [Dining PIR]: NotReady
[2/8/2022, 7:57:34 AM] [Omni] Zone 12 [Dining PIR]: Ready
```
I've also been looking at how best to support the audio zones in HomeKit. I'm finding that audio devices in general are poorly supported by Apple. So far the best I can probably do is set each audio zone as a TV accessory. This will allow you to select your different audio sources but to control the volume you'll need to go into the Control Center's Remote app

**Comment by dfrank811** [comment]
I will check the logs this evening and get back to you.

I would love to just be able to see the zones and have the ability to
toggle them on or off.  Mostly for turning them off.  Sometimes I forget
and leave some on and I would love to be able to have them part of a
goodnight scene to turn them off.

**Comment by mantorok1** [comment]
You should be able to turn the zones on & off from within the TV accessory. It's just the volume controls (include mute) that can't be controlled from within the Home app.

**Comment by dfrank811** [comment]
Ok, I just realized that I had turned off the logging for omni events.

It is logging when I turn a zone on and off.  It also logs when I change
the source of the zone.

David

**Comment by mantorok1** [comment]
That's great news. Thanks.

**Comment by mantorok1** [comment]
Hi @dfrank811, I've just published version 1.5.4 of the plugin which includes HomeKit integration for Audio Zones & Sources. If you don't mind could you please be my beta tester and make sure all the functionality works correctly. Start by reading the "Audio Zones" section of the README which explains the functionality and how you add them to HomeKit.
Please report back here with what works and what doesn't.
Thanks in advance.

**Comment by mantorok1** [comment]
Hi @dfrank811, did you have a chance to test the new version? Is it working ok? Just wondering if I can close this issue.

**Comment by dfrank811** [comment]
I was rebuilding my home network so a lot of it was down for a while.  I
did update it last night and everything seemed to work fine until I added
the first speaker accessory. It seemed to work fine, but then showed as not
responding. Then every accessory from my Omni panel started showing not
responding.  Still this morning they don’t respond.  I have tried
restarting the bridge but that did not work.
I guess the next step is to remove and re-add the bridge but I was hoping
to avoid that since I have a lot of switches that I will need to put in the
correct rooms again.

Do you have any thoughts?

**Comment by mantorok1** [comment]
Was there anything in the HB logs relating to the accessories not responding? Try turning on `showOmniEvents` and `showRequestResponse` to get more details in the logs.

Another thing you could try before removing the whole plugin is just remove the speaker accessory. You can do this from the Home app, just scroll to the bottom of the accessory's config where you should see a "Remove accessory" option. It effectively runs in its own bridge so should be independent of the other Omni accessories. If you do this make sure you follow the Troubleshooting section under "Audio Zones" in the README to delete those files. Otherwise you won't be able to re-add it again.

**Comment by dfrank811** [comment]
I think my OmniPro 2 panel just died.  I am planning to switch over to a
PulseWorx PCS Gateway to control all of my lights but unfortunately I have
not found a homebridge plugin for that.

**Comment by mantorok1** [comment]
Sorry to hear that. Hope you find a suitable solution.
Shall we close this issue?

**Comment by dfrank811** [comment]
Yeah it looked like it was working before my panel started failing. Thank
you for all your help.
