### ISSUE TITLE
How do i configure this so it knows all my bulbs are dimmable without configuring them one a t a time 

### ISSUE THREAD

**Issue by Tesla-P100FX** [mantorok1/homebridge-omnilink-platform#16]
i am including all lights and only excluding those that dont work.    Is there a simple way to say these are dimmable?

            "includeAreas": true,
            "includeZones": true,
            "securityCode": "1968",
            "includeButtons": false,
            "includeUnits": true,
            "includeAuxiliarySensors": false,
            "includeEmergencyAlarms": false,
            "exclude": {
                "units": "17,22,28,33,58,59"
            },
            "defaultAccessoryMappings": {
                "zone": "none",
                "zoneFireEmergency": "none"
            },
            "map": {
                "zones": {
                    "contact": "8,15,24,29,32,39,40,48,49"
                }
            },
            "syncTime": true,
            "showHomebridgeEvents": true,
            "showOmniEvents": false,
            "showRequestResponse": false,
            "clearCache": false
        }
    ]
}

**Comment by mantorok1** [comment]
Hi @Tesla-P100FX, the `lightbulb` is the one to use for dimmable lights. You can set the default to be `lightbulb` with something like:
```
        "defaultAccessoryMappings": {
            "zone": "none",
            "zoneFireEmergency": "none",
            "unit": "lightbulb"
        },
```
This will tell the plugin that any unit that is not explicitly excluded or mapped to be a `lightbulb` accessory in HomeKit

**Comment by Tesla-P100FX** [comment]
Thanks 🙏,  easy fix!


Thanks

***@***.***

Sent from my Phone 📞, please excuse typos and amusing  autocorrects


On Apr 5, 2022, at 3:48 PM, mantorok1 ***@***.***> wrote:

﻿

Hi @Tesla-P100FX<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTesla-P100FX&data=04%7C01%7C%7C85f1f61f173f4f686f1808da175657af%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637847956862508942%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Xor4CAJE1%2BgUEmlXJ0L5jtyX%2FcljICJxamCaVQzIcLw%3D&reserved=0>, the lightbulb is the one to use for dimmable lights. You can set the default to be lightbulb with something like:

        "defaultAccessoryMappings": {
            "zone": "none",
            "zoneFireEmergency": "none",
            "unit": "lightbulb"
        },


This will tell the plugin that any unit that is not explicitly excluded or mapped to be a lightbulb accessory in HomeKit
