### ISSUE TITLE
MQTT ECONNREFUSED 

### ISSUE THREAD

**Issue by btgh** [mantorok1/homebridge-omnilink-platform#17]
**Describe Your Problem:**
I'm having a problem authenticating with MQTT from home bridge but it works find from the mosquito client 

**Logs:**

```
 [Omni] Failed to connect to MQTT broker. Error: connect ECONNREFUSED 192.168.10.9:1883
 [Omni] Will try again in 1 minute
```

**Plugin Config:**

```json
"mqtt": {
                "host": "mqtt://192.168.10.9",
                "port": 1883,
                "username": "omni",
                "password": "password",
                "topicPrefix": "sandwich_omni",
                "showMqttEvents": true
            },
```

**Screenshots:**

**Environment:**

* **Plugin Version**:1.5.5
* **Homebridge Version**: 1.4.1
* **Node.js Version**: 16.15.1
* **NPM Version**: 8.5.1
* **Operating System**: Ubuntu

**Comment by mantorok1** [comment]
Hi @btgh, it sounds like a network connectivity issue between homebridge and the MQTT broker
Could you please start a Terminal session from the Homebridge UI menu and type the following:
```
nc -vz 192.168.10.9 1883
```
If its able to connect you should see a message like:
```
192.168.10.9 (192.168.10.9:1883) open
```
If there's no message or some other message its likely a network issue

**Comment by Tesla-P100FX** [comment]
Why that ip adress?   My ip adress of the Omni link controller   is 10.0.0.252

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mantorok1** [comment]
Its not a connectivity issue with the Omni, it looks like its with the MQTT broker. Based on your config the broker's ip address is `192.168.10.9`

**Comment by btgh** [comment]
I should have mentioned that both homebridge and mosquito are on the same Ubuntu machine - localhost gives the same result.  From the terminal I get a failed connection using nc but isn't that the correct behavior since I'm not authenticating with mqtt server?  I can connect using the mosquito tools running in the homebrindge terminal window (via browser on my Mac).  


Homebridge Terminal

Node.js Version: v16.15.1
Node.js Path: /opt/homebridge/bin/node
Plugin Path: /var/lib/homebridge/node_modules

Update Node.js: hb-service update-node

Install Plugin: hb-service add homebridge-plugin-name
Remove Plugin: hb-service remove homebridge-plugin-name

homebridge@homebridge-PC:/var/lib/homebridge $ nc -vz 192.168.10.9 1883
nc: connect to 192.168.10.9 port 1883 (tcp) failed: Connection refused
homebridge@homebridge-PC:/var/lib/homebridge $ mosquitto_sub -u omni -P 047b85 -t "sandwich_omni" -p 1883
hello hombridge
homebridge@homebridge-PC:/var/lib/homebridge $ mosquitto_pub -u omni -P 047b85 -t "sandwich_omni" -p 1883 -m "hello from homebridge"
homebridge@homebridge-PC:/var/lib/homebridge $ 

terminal season on same machine:
homebridge-PC:~$ mosquitto_pub -u omni -P 047b85 -t "sandwich_omni" -p 1883 -m "hello hombridge"
homebridge-PC:~$ mosquitto_sub -u omni -P 047b85 -t "sandwich_omni" -p 1883
hello from homebridge:

**Comment by mantorok1** [comment]
Before any authentication can occur the plugin needs to be able to connect to the port. As its saying "connection refused" there is something blocking it.
It's odd that `mosquitto_sub` can connect ok though. Perhaps a firewall rule is blocking Homebridge from connecting to the mosquitto broker but allowing `mosquitto_sub`?
What happens if you run the above `nc` command on the normal Ubuntu terminal?

**Comment by btgh** [comment]
looks like a security feature was added to mosquito requiring explicit access to the LAN IP.  Once I added the following  to the default.conf file mqtt now works fine.

listener 1883 127.0.0.1
listener 1883 192.168.10.9

**Comment by mantorok1** [comment]
Hi @btgh, interesting find. I checked my own config file which has:
```
listener 1883
```
Maybe that allows access from any IP address. I haven't upgraded mosquitto in a while though so its possible that may not work anymore.
BTW, you're the first person I know that is using MQTT on my omnilink plugin (I don't use it myself). Let me know how it goes or if there's any issues with it.
