### ISSUE TITLE
Two of my thermostats report current temp as -41 

### ISSUE THREAD

**Issue by Tesla-P100FX** [mantorok1/homebridge-omnilink-platform#18]
Two of my thermostats report current temp as -41.  The temp is accurate on the actual physical Thermostats just not being read  properly by my controller.  **Its  not a OmniLink issue as SNAP-Link shows the temp as zero**.   Just wondering if you have thoughts on what might cause that.  I have 9 thermostats.  The rest work fine.  

HomeBridge 1.3.4
Node 16.15.1 
OmniLink 1.5.5

Config.json 
 "includeAreas": true,
        "includeZones": true,
        "securityCode": "1968",
        "includeButtons": false,
        "includeUnits": true,
        "includeAuxiliarySensors": false,
        "includeEmergencyAlarms": false,
        "exclude": {
            "units": "17,22,28,33,58,59"
        },
        "defaultAccessoryMappings": {
            "zone": "none",
            "zoneFireEmergency": "none"
        },
        "map": {
            "zones": {
                "contact": "8,15,24,29,32,39,40,48,49"
            }
        },
        "syncTime": true,
        "showHomebridgeEvents": true,
        "showOmniEvents": false,
        "showRequestResponse": false,
        "clearCache": false
    }
]
}

**Comment by mantorok1** [comment]
Hi @Tesla-P100FX, I'll need a bit more info from you before I can find the cause of the issue. Could you please enable the logging of Requests & Responses. After restarting homebridge you'll see log messages that looks like:
```
Response: {a list of numbers} [{ResponseName}]
``` 
Example:
```
Response: 33,7,59,1,4,0,8,1,254,58,230,0,0,0 [ExtendedZoneStatusResponse]
```
The ones I'm looking for are where the ResponseName is `ExtendedThermostatStatusResponse` and `ThermostatPropertiesResponse`

**Comment by Tesla-P100FX** [comment]
Response: 33,31,33,6,0,1,1,0,113,136,0,0,0,3,70,114,111,110,116,32,68,111,111,114,0,0,0,255,0,0,0,0,0,128,25,0,0,0,0,0,0,0,0,0,0,0 [ThermostatPropertiesResponse]
6/17/2022, 8:01:45 AM Omnilink Platform Bridge Omni Request: 33,8,32,6,0,2,0,1,0,0
6/17/2022, 8:01:45 AM Omnilink Platform Bridge Omni Response: 33,31,33,6,0,2,0,126,126,149,1,0,0,3,77,97,115,116,101,114,32,66,97,116,104,0,0,255,0,0,0,0,0,237,183,0,0,0,0,0,0,0,0,0,0,0 [ThermostatPropertiesResponse]
6/17/2022, 8:01:45 AM Omnilink Platform Bridge Omni Request: 33,8,32,6,0,3,0,1,0,0
6/17/2022, 8:01:45 AM Omnilink Platform Bridge Omni Response: 33,31,33,6,0,3,0,116,114,142,1,0,255,3,76,97,117,114,101,110,32,66,101,100,114,109,0,255,0,0,0,0,0,221,79,0,0,0,0,0,0,0,0,0,0,0 [ThermostatPropertiesResponse]
6/17/2022, 8:01:45 AM Omnilink Platform Bridge Omni Request: 33,8,32,6,0,4,0,1,0,0
6/17/2022, 8:01:45 AM Omnilink Platform Bridge Omni Response: 33,31,33,6,0,4,0,122,122,134,0,0,0,3,77,97,116,104,101,119,39,115,32,0,0,0,0,255,0,0,0,0,0,98,163,0,0,0,0,0,0,0,0,0,0,0 [ThermostatPropertiesResponse]
6/17/2022, 8:01:45 AM Omnilink Platform Bridge Omni Request: 33,8,32,6,0,5,0,1,0,0
6/17/2022, 8:01:45 AM Omnilink Platform Bridge Omni Response: 33,31,33,6,0,5,1,0,120,142,1,0,0,3,77,97,115,116,101,114,32,66,101,100,114,109,0,255,0,0,0,0,0,121,151,0,0,0,0,0,0,0,0,0,0,0 [ThermostatPropertiesResponse]
6/17/2022, 8:01:45 AM Omnilink Platform Bridge Omni Request: 33,8,32,6,0,6,0,1,0,0
6/17/2022, 8:01:45 AM Omnilink Platform Bridge Omni Response: 33,31,33,6,0,6,0,126,121,145,0,1,0,3,82,105,99,104,39,115,32,79,102,102,105,99,0,255,0,0,0,0,0,232,193,0,0,0,0,0,0,0,0,0,0,0 [ThermostatPropertiesResponse]
6/17/2022, 8:01:45 AM Omnilink Platform Bridge Omni Request: 33,8,32,6,0,7,0,1,0,0
6/17/2022, 8:01:45 AM Omnilink Platform Bridge Omni Response: 33,31,33,6,0,7,0,124,120,138,1,0,0,3,68,105,110,105,110,103,32,82,111,111,109,0,0,255,0,0,0,0,0,189,223,0,0,0,0,0,0,0,0,0,0,0 [ThermostatPropertiesResponse]
6/17/2022, 8:01:45 AM Omnilink Platform Bridge Omni Request: 33,8,32,6,0,8,0,1,0,0
6/17/2022, 8:01:45 AM Omnilink Platform Bridge Omni Response: 33,31,33,6,0,8,0,117,116,139,1,0,0,3,75,105,116,99,104,101,110,32,72,97,108,108,0,255,0,0,0,0,0,194,234,0,0,0,0,0,0,0,0,0,0,0 [ThermostatPropertiesResponse]
6/17/2022, 8:01:45 AM Omnilink Platform Bridge Omni Request: 33,8,32,6,0,9,0,1,0,0
6/17/2022, 8:01:45 AM Omnilink Platform Bridge Omni Response: 33,31,33,6,0,9,0,118,118,149,1,0,0,3,76,97,117,114,101,110,32,66,97,116,104,0,0,255,0,0,0,0,0,220,33,0,0,0,0,0,0,0,0,0,0,0 [ThermostatPropertiesResponse]
6/17/2022, 8:01:45 AM Omnilink Platform Bridge Omni Request: 33,8,32,8,0,16,0,0,0,0
6/17/2022, 8:01:45 AM Omnilink Platform Bridge Omni Response: 33,26,33,8,0,16,0,96,0,0,82,84,104,101,114,109,111,115,116,97,116,115,0,0,0,0,0,1,213,147 [AuxiliarySensorPropertiesResponse]
6/17/2022, 8:01:45 AM Omnilink Platform Bridge Omni Request: 33,8,32,8,0,88,0,0,0,0
6/17/2022, 8:01:46 AM Omnilink Platform Bridge Omni Response: 33,26,33,8,0,88,0,109,0,0,81,84,101,109,112,32,83,101,110,46,32,79,117,116,100,114,0,1,63,148 [AuxiliarySensorPropertiesResponse]
6/17/2022, 8:01:46 AM Omnilink Platform Bridge Omni Request: 33,6,58,5,0,1,0,1
6/17/2022, 8:01:46 AM Omnilink Platform Bridge Omni Response: 33,9,59,5,6,0,1,0,0,0,0,108,225,0 [ExtendedAreaStatusResponse]
6/17/2022, 8:01:46 AM Omnilink Platform Bridge Omni Request: 33,6,58,1,0,1,0,90
6/17/2022, 8:01:46 AM Omnilink Platform Bridge Omni Response: 33,1,2,128,81,0,0,0,0,0,0,0,0,0 [AcknowledgeResponse]
6/17/2022, 8:01:46 AM Omnilink Platform Bridge Omni Request: 33,6,58,2,0,9,0,225
6/17/2022, 8:01:46 AM Omnilink Platform Bridge Omni Response: 33,1,2,128,81,0,0,0,0,0,0,0,0,0 [AcknowledgeResponse]
6/17/2022, 8:01:46 AM Omnilink Platform Bridge Omni Request: 33,6,58,6,0,1,0,9
6/17/2022, 8:01:46 AM Omnilink Platform Bridge Omni Response: 33,129,59,6,14,0,1,1,0,113,136,0,0,0,0,0,0,0,0,0,2,0,126,126,149,1,0,0,0,0,0,0,0,0,3,0,116,114,142,1,0,255,0,0,0,0,0,0,4,0,122,122,134,0,0,0,0,0,0,0,0,0,5,1,0,120,142,1,0,0,0,0,0,0,0,0,6,0,126,121,145,0,1,0,0,0,0,0,0,0,7,0,124,120,138,1,0,0,0,0,0,0,0,0,8,0,117,116,139,1,0,0,0,0,0,0,0,0,9,0,118,118,149,1,0,0,0,0,0,0,0,195,83,0,0,0,0,0,0,0,0,0 [ExtendedThermostatStatusResponse]
6/17/2022, 8:01:46 AM Omnilink Platform Bridge Omni Thermostat 1 [Front Door]: -40C; Off
6/17/2022, 8:01:46 AM Omnilink Platform Bridge Omni Thermostat 2 [Master Bath]: 23C; Heat
6/17/2022, 8:01:46 AM Omnilink Platform Bridge Omni Thermostat 3 [Lauren Bedrm]: 18C; Heat
6/17/2022, 8:01:46 AM Omnilink Platform Bridge Omni Thermostat 4 [Mathew's]: 21C; Off
6/17/2022, 8:01:46 AM Omnilink Platform Bridge Omni Thermostat 5 [Master Bedrm]: -40C; Heat
6/17/2022, 8:01:46 AM Omnilink Platform Bridge Omni Thermostat 6 [Rich's Offic]: 23C; Off
6/17/2022, 8:01:46 AM Omnilink Platform Bridge Omni Thermostat 7 [Dining Room]: 22C; Heat
6/17/2022, 8:01:46 AM Omnilink Platform Bridge Omni Thermostat 8 [Kitchen Hall]: 18.5C; Heat
6/17/2022, 8:01:46 AM Omnilink Platform Bridge Omni Thermostat 9 [Lauren Bath]: 19C; Heat

**Comment by mantorok1** [comment]
The current temperature is the 8th number in the `ThermostatPropertiesResponse`. The values range from 0 (-40C/-40F) to 255 (87.5C/189.5F)
Looking at the response for Thermostat 1, the 8th value is zero which is why its showing as -40.
```
33,31,33,6,0,1,1,0,...
```
Compare that to Thermostat 2 where the 8th value is 126 which is 23C/73.4F
```
33,31,33,6,0,2,0,126,...
```
I suspect the SnapLink app has some logic the will display a minimum temp of zero if the temp is in the negative range

**Comment by mantorok1** [comment]
Hi @Tesla-P100FX, I've just released a new version (1.5.6) of the plugin that includes the ability to define an allowed temperature range for the thermostats. This should hopefully solve your problem where some thermostats are showing -40.
I'm not able to test this functionality so if you could provide some feedback that would be great.

**Comment by Tesla-P100FX** [comment]
> Hi @Tesla-P100FX, I've just released a new version (1.5.6) of the plugin that includes the ability to define an allowed temperature range for the thermostats. This should hopefully solve your problem where some thermostats are showing -40.
> 
> I'm not able to test this functionality so if you could provide some feedback that would be great.

Great thanks for making this change. I'll install it and let you know the results 😀

**Comment by Tesla-P100FX** [comment]
Installed today!   New temp shows as 32F. Thanks.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mantorok1** [comment]
Cool. Thanks for letting me know.
