### ISSUE TITLE
Omni Event Log in Homebridge

### ISSUE THREAD

**Issue by btgh** [mantorok1/homebridge-omnilink-platform#21]
**Is your feature request related to a problem? Please describe:**

In my omni automation I explicitly write to the event log for notifications I care most about.  I would like to show the Omni event log in homebridge without logging all the other omni events such as sensor updates.  For example, the temperature sensors write frequent updates which fill the log quickly with "unimportant events" making it difficult to find a history of when a perimeter sensor was tripped.  

**Describe the solution you'd like:**

A  new option to only show what is written to the Omni Event log in the homebridge log instead of all events.  Ideally there would be a way to show the omni event log in the home app - but I don't think this is supported by HomeKit. 

**Describe alternatives you've considered:**

**Additional context:**

**Comment by mantorok1** [comment]
At the moment the plugin will write all supported Omni events to the Homebridge log. I'll see if its possible for the plugin to apply a filter so the user can define only the events they are interested in but it will likely be at an object level (eg. zones, units, thermostats etc)

Another option you could look into is MQTT. The plugin does support it and you can just subscribe to the event you are interested in such as your perimeter sensors.

**Comment by mantorok1** [comment]
Hi @btgh, version 1.5.10 has been released which allows you to exclude zone status changes and temperature changes from the Homebridge log (they are under "Other Settings").
I'm not able to test the latter as I don't have any thermostats or auxiliary sensors connected to my Omni. Would you mind testing it out for me and let me know how it goes. Thanks

**Comment by btgh** [comment]
@mantorok1 I tested for both cases and the option works as expected - thanks for the enhancement
