### ISSUE TITLE
not detecting my zones after install

### ISSUE THREAD

**Issue by zcserijr** [mantorok1/homebridge-omnilink-platform#22]
I have installed the plugin and my system is not discovering my zones. It only finds one zone, "zone 9". 
I am not sure if I have setup the plugin incorrectly, as i only made minimal changes such as adding my keys, security code number, etc. I did disable my thermostats (which never really worked) using PCaccess, in order to see if it would help, but it did not. 

[homebridgelog.docx](https://github.com/mantorok1/homebridge-omnilink-platform/files/9946594/homebridgelog.docx)

[jsconfig.docx](https://github.com/mantorok1/homebridge-omnilink-platform/files/9946602/jsconfig.docx)

* **Plugin Version**: v1.5.7
* **Homebridge Version**: v4.49.0
* **Node.js Version**: v16.16.0
* **NPM Version**: 
* **Operating System**:  Raspbian

**Comment by zcserijr** [comment]
While trouble shooting, I noticed that the only zone that was being detected was named as 'Zone 9. The other zones did not have an apostrophe in the name, ie Zone 5, zone 6. After placing the apostrophe in the name of the others, they now show up. ie 'Zone 5, 'Zone 6, etc. 

I have noticed a different issue. The buttons used to bypass a zone don't have any effect. The log shows the following when I try to activate one: 


[06/11/2022, 14:27:55] [Omni] Bypass 'ZONE 13: Setting characteristic 'On' to 'true'
[06/11/2022, 14:27:55] [Omni] Request: 33,6,38,1,1,1,1,1
[06/11/2022, 14:27:55] [Omni] Response: 33,3,39,1,1,112,31,0,0,0,0,0,0,0 [SecurityCodeValidationResponse]
[06/11/2022, 14:27:55] [Omni] Zone 13 ['ZONE 13]: Set Bypass failed [Cannot read properties of undefined (reading 'name')]

**Comment by mantorok1** [comment]
Hi @zcserijr, yes the plugin will only pickup named zones. As you've found prefixing an apostrophe will do the job but you may want to name the zones to something more meaningful such as the room they refer to.

I suspect the bypass issue is related in to an unnamed security code. Again the plugin only reads named ones so to fix you probably just need to set its name to something like your name (using PC Access). This is similar to [issue #20](https://github.com/mantorok1/homebridge-omnilink-platform/issues/20)

Let me know how it goes.

**Comment by zcserijr** [comment]
Thank you. I did not realize that the names of the zones had to be different from the default names in the software. The bypass issue was fixed, not by naming the security code, but by naming the Area of my system. That was a little glitchy, because I only have one area in my security system, so it was not even listed for me to give it a name. I had to temporarily set my system to have 2 areas, so I could name the first one, then set it back to 1 area. That seemed to work. 

I can see my thermostats now, and I can change their mode. 
The only problem is that I cannot change the temperature setpoint. So, I will try and look into that.

**Comment by mantorok1** [comment]
Glad to hear you sorted it out. I'm not sure why the Area needs to be named for the Bypass to work. Its about the only thing that the plugin doesn't need to be named. My own Area is not named.

I don't have any thermostats on my own Omni. If you can't resolve the setpoint issue let me know and provide logs like you've done before and I'll see what I can do.

**Comment by zcserijr** [comment]
It seems the reason I was not able to control the temperature setpoint is because I have my thermostat "HOLD" setting "ON". If I change "HOLD" to "OFF", then I can alter the temperature setpoint. I just have to run my thermostat on a program, which I typically have not done.
