### ISSUE TITLE
support for node.js 18.12.1

### ISSUE THREAD

**Issue by btgh** [mantorok1/homebridge-omnilink-platform#23]
The plugin "homebridge-omnilink-platform" requires Node.js version of ^14.18.2 || ^16.13.1 which does not satisfy the current Node.js version of v18.12.1. You may need to upgrade your installation of Node.js.

**Comment by mantorok1** [comment]
Hi @btgh, I've released version 1.5.8 which should address this issue.

**Comment by btgh** [comment]
that fixed it - thanks!
