### ISSUE TITLE
one of my thermostats is constantly throwing an error- Omnilink Platform Bridge 9864@Front Door@Front Door@Target Heating Cooling State

### ISSUE THREAD

**Issue by Tesla-P100FX** [mantorok1/homebridge-omnilink-platform#24]
**Describe Your Problem:**
one of my thermostats is constantly throwing an error(100s of erros daily) and i just want to remove it but unsure how to or what unit number it is 

**Logs:**

```
Omnilink Platform BridgeERROR[Omnilink Platform Bridge 9864@Front Door@Front Door@Target Heating Cooling State] characteristic was supplied illegal value: number 3 exceeded maximum of 1
1/24/2023, 11:55:36 AMOmnilink Platform BridgeERROR[Omnilink Platform Bridge 9864@Front Door@Front Door@Target Heating Cooling State] characteristic was supplied illegal value: number 3 exceeded maximum of 1
1/24/2023, 2:42:05 PMOmnilink Platform Bridge
```

**Plugin Config:**

```json

{
    "accessories": [],
    "platforms": [
        {
            "platform": "OmniLinkPlatform",
            "name": "Omni",
            "port": 4369,
            "targetHumidityDifference": 0,
            "key1": ""
            "address": "10.0.0.252",
            "key2": "",
            "includeAreas": true,
            "includeZones": true,
            "securityCode": "",
            "includeButtons": false,
            "includeUnits": true,
            "includeAuxiliarySensors": false,
            "includeEmergencyAlarms": false,
            "exclude": {
                "units": "17,22,28,33,58,59"
            },
            "defaultAccessoryMappings": {
                "zone": "none",
                "zoneFireEmergency": "none",
                "unit": "lightbulb"
            },
            "map": {
                "zones": {
                    "contact": "8,15,24,29,32,39,40,48,49"
                }
            },
            "syncTime": true,
            "showHomebridgeEvents": false,
            "showOmniEvents": false,
            "showRequestResponse": false,
            "clearCache": false,
            "mqtt": {
                "showMqttEvents": false
            }
        }
    ]
}
```

**Screenshots:**

**Environment:**

* **Plugin Version 1.5.9
* **Homebridge Version** 1.5.0
* **Node.js Version**:  16.19.0
* **NPM Version**: 
* **Operating System**: Raspbian

**Comment by mantorok1** [comment]
Hi @Tesla-P100FX,
The error indicates that the thermostat only supports OFF (0) and HEAT (1) modes but it's trying to be set to AUTO (3) mode. Do you know if it should support COOL (2) and AUTO modes? Maybe there's bug and the plugin is not picking up the correct capacities of your system. I can try to fix it but I may need you to gather some more info for me.

If you just want to exclude it add `thermostats` to the `exclude` key like:
```
            "exclude": {
                "units": "17,22,28,33,58,59",
                "thermostats": "1"
            },
```
It looks like it's the thermostat named `Front Door` that is causing the issue. You just need to figure out its number so you can add it to the above `thermostats` key. You can do that by using "PC Access" or just restart the plugin (or homebridge) and it will give you a summary (name and number) of all your zones, units, thermostats etc. in the log.
Failing that all I can suggest is you try one at a time until you find the problem thermostat.

**Comment by Tesla-P100FX** [comment]
All my thermostats I think only support on and heat.  Old house with Radiators an no forced air.   They are all like that..  No cool, no auto.

I don't see the thermostat in "Units" would it be a zone.  See Zone 8.

***@***.***

**Comment by mantorok1** [comment]
I believe Thermostats are different to units and zones from the Omni controller point of view. When you restart homebridge does it show any thermostats in the logs? In my case I don't have any so I see this:
```
[1/26/2023, 11:43:21 AM] [Omni] Units found: 3
[1/26/2023, 11:43:21 AM] [Omni]    33: Strobe            [Output]
[1/26/2023, 11:43:21 AM] [Omni]    34: Garage Door       [Output]
[1/26/2023, 11:43:21 AM] [Omni]    41: GARAGE DOOR       [Flag]
[1/26/2023, 11:43:21 AM] [Omni] Buttons found: 1
[1/26/2023, 11:43:21 AM] [Omni]     1: Garage Door
[1/26/2023, 11:43:21 AM] [Omni] Thermostats found: 0
[1/26/2023, 11:43:21 AM] [Omni] Access Controls found: 0
[1/26/2023, 11:43:21 AM] [Omni] Auxiliary Sensors found: 0
[1/26/2023, 11:43:21 AM] [Omni] Audio Sources found: 0
[1/26/2023, 11:43:21 AM] [Omni] Audio Zones found: 0
```

**Comment by mantorok1** [comment]
Hi @Tesla-P100FX,
Did you manage to exclude the `Front Door` thermostat? Just wondering if I can close this issue

**Comment by Tesla-P100FX** [comment]
No but I suppose you can close I no longer can get pC access to run so don't know the unit number.  DO you have access to a version of PC access that works

**Comment by Tesla-P100FX** [comment]
Is it these numbers?  So just exclude 1

***@***.***

**Comment by Tesla-P100FX** [comment]
sorry for multiple mails.   Figured it out, working 😊 As always thank you !

**Comment by mantorok1** [comment]
Glad to hear you sorted it out.

If you still interesting is getting a copy of PC Access someone posted links in [issue #5](https://github.com/mantorok1/homebridge-omnilink-platform/issues/5#issuecomment-842473013)

**Comment by Tesla-P100FX** [comment]
Sure if you have easy access, I’m. It sure I am running what was the last version? 3.9?


Thanks

***@***.***

Sent from my Phone 📞, please excuse typos and amusing  autocorrects


On Apr 22, 2023, at 1:38 PM, mantorok1 ***@***.***> wrote:

﻿

Glad to hear you sorted it out.

If you still interesting is getting a copy of PC Access someone posted links in issue #5<https://github.com/mantorok1/homebridge-omnilink-platform/issues/5#issuecomment-842473013>

**Comment by mantorok1** [comment]
Sorry I'm not sure what you mean by "easy access". Can you not download either of the files?
Here's the links again:
* [Setup_HAI_PC_Access_3.exe](https://pc-access-3.s3.amazonaws.com/PCA3U_EN/Setup_HAI_PC_Access_3.exe)
* [Setup_HAI_Dealer_PC_Access_3.exe](https://pc-access-3.s3.amazonaws.com/PCA3D_EN/Setup_HAI_Dealer_PC_Access_3.exe)

The Dealer PC Access is version 3.17. The initial password to gain entry to the app is `PASSWORD`
