### ISSUE TITLE
Thermostat hold control from Homebridge

### ISSUE THREAD

**Issue by btgh** [mantorok1/homebridge-omnilink-platform#27]
**Is your feature request related to a problem? Please describe:**

If the omni stats are not kept on hold, the default thermostat schedule will take over - instead of the OMNI controller being the master.  Homekit doesn’t seem to support a hold switch for thermostats.  If the temperature is changed in homekit while the thermostat is in hold, it will jump back to the previous temp.  To work around this I’ve implemented a button to toggle the hold of each thermostat, but it’s rather clunky.  

**Describe the solution you'd like:**

Is there a “thermostat change event” that can be caught in homebridge to remove the hold, in order to modify the temp and then activate hold once the temp has changed?

**Describe alternatives you've considered:**

**Additional context:**

**Comment by mantorok1** [comment]
Hi @btgh,
I wasn't too sure what is the best way to implement the "Hold" mode in HomeKit. As I don't have any thermostats connected to my Omni I don't know what its purpose is or how it functions.

From what you've describe I gather you want it to work like this:
1. User changes the SetPoint (or target) temperature in the HomeKit thermostat
2. If the Omni thermostat is in Hold mode then turn it off
3. Set the Omni thermostat's SetPoint to the one selected by the user (in step 1)
4. If the Omni thermostat was previously in the Hold mode (step 2) then turn it back on 

So there is no need for a seperate switch in HomeKit to turn the Hold mode on and off, is that correct?

**Comment by btgh** [comment]
You’ve capture it correctly On Apr 16, 2023, at 3:42 AM, mantorok1 ***@***.***> wrote:﻿
Hi @btgh,
I wasn't too sure what is the best way to implement the "Hold" mode in HomeKit. As I don't have any thermostats connected to my Omni I don't know what its purpose is or how it functions.
From what you've describe I gather you want it to work like this:

User changes the SetPoint (or target) temperature in the HomeKit thermostat
If the Omni thermostat is in Hold mode then turn it off
Set the Omni thermostat's SetPoint to the one selected by the user (in step 1)
If the Omni thermostat was previously in the Hold mode (step 2) then turn it back on

So there is no need for a seperate switch in HomeKit to turn the Hold mode on and off, is that correct?

**Comment by mantorok1** [comment]
Hi @btgh,
I've released version 1.5.11 of the plugin which should resolve this issue (but I'm not able to test it on my own system). Please try it out and let me know how it goes.

**Comment by btgh** [comment]
Works great!  Thanks for the enhancement.
