### ISSUE TITLE
Hey.    Don’t have an issue as I have not installed yet.   Today I run homeseer onPi and then I connect a HomeKit plugin to homeseer.  Love to eliminate homeseer and go direct.   How many people do you have using the plug in now?   Looks like I can use the default setting and won’t have to add specific devices.  That would be great as I have 30+ devices.

### ISSUE THREAD

**Issue by Tesla-P100FX** [mantorok1/homebridge-omnilink-platform#3]
**Describe Your Problem:**

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by mantorok1** [comment]
Hi @Tesla-P100FX, I'm not really sure how many use the plugin but I'd guess somewhere between 50 and 100 based on how many weekly downloads I'm getting. There was a weird spike of nearly 2000 downloads back in October 2020 but I don't think they were genuine users of the plugin (but I could be wrong).
As I said before though, if you have issues getting it working please provide the following details and I'll see if I can help you out:

- Homebridge version
- Plugin version
- Copy of the config.json file (with sensitive information removed)
- Copy of Homebridge logs (with Homebridge in DEBUG mode)
