### ISSUE TITLE
Have HomeKit event activate keypad.

### ISSUE THREAD

**Issue by Tesla-P100FX** [mantorok1/homebridge-omnilink-platform#30]
We have a fence with a gate at the front of our home with an Omni pro connected contact sensor on it.    When the gate opens our console beeps 3 times.    I have added a contact sensor to HomeKit (not our Omni pro)  and would like to tell my  Omni pro to beep the console?   Do you know how I might do that?

**Comment by mantorok1** [comment]
Hi @Tesla-P100FX, I'm not sure how to do that. You could try asking in this forum, there are some very knowledgeable people in there: https://cocoontech.com/forum/leviton-hai-omnipro/
