### ISSUE TITLE
HomeKit Audio Control via remote app for speakers unable to increase volume

### ISSUE THREAD

**Issue by bloggermanic** [mantorok1/homebridge-omnilink-platform#33]
**Describe The Bug:**

HomeKit Audio Control via remote app for speakers unable to increase volume. It only decreases volume. As an example if the volume is 50%. Pushing the upper side button to increase volume only decreases it. It does not go to 0% but stays at 14%
I'm happy you work with you to improve this and other aspects of the plugin. 

**To Reproduce:**

Select the HomeKit speaker via the remote app. As an example the volume is initially set to 50%. Pushing the upper side button to increase volume only decreases it. It does not go to 0% but stays at 14%

**Expected behavior:**

I expect the up and down volume buttons to increase or decrease volume. 

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by mantorok1** [comment]
Thanks for letting me know about the issue. Does using the up arrow button in the remote app behave the same as the volume up side button?

I won't be able to look into this for about a week but in the meantime could you turn on the request & response logs and capture what commands are being sent to the Omni controller when you press the volume buttons and what reply is coming back

**Comment by bloggermanic** [comment]
Ok. I'll turn it on

**Comment by mantorok1** [comment]
Hi @bloggermanic, I've had a look at the code and can't see anything obvious that would be causing the behaviour you've described. I'll need those logs to look into it any further so could you enable the following options:

- Show Omni notification events in the log
- Show Request and Responses in the log

In particular I'm looking for the ones that look like this (and those just before and after it):
```
Set volume to ...
```

**Comment by bloggermanic** [comment]
Wow it's working now. Much appreciated. Loving it. Just something minor, but I notice the mute button does not work. 

Thank you so much!!

**Comment by mantorok1** [comment]
That's great. Thanks for letting me know.

For the mute issue can you provide the logs requested above. In this case I'm looking for ones that look like:
```
Set state to MuteOff/MuteOn
```

**Comment by mantorok1** [comment]
Hi @bloggermanic, which Mute button were you referring to? The plugin uses the SELECT button (the one in the centre of the arrow buttons) to toggle the Mute. There is also a specific Mute button in the top left of the Remote app screen - I found that I hadn't implemented this one.  I've just released ver 1.5.16 which now implements it.
If you could try it out and see if both methods of toggling the mute now functions correctly. If not providing those logs will help me to troubleshoot the issue. Thanks

**Comment by bloggermanic** [comment]
I'll try it

**Comment by bloggermanic** [comment]
Okay here's the update. 
Volume:
The volume is working via the up and down buttons on screen. It was working with the phones side volume buttons, but it does not seem possible now. 

Mute:
And the mute button is working via the center on screen button. 


Speaker Icon:
I was expecting the speaker icon above to be the un/mute button. But I guess is fine that it does not work

Power Icon:
The power icon button only appears to turn on the audio, but it does not turn off. 


![image](https://github.com/mantorok1/homebridge-omnilink-platform/assets/74580384/3b598b69-62f1-4967-9aca-2605ec1eaffa)

**Comment by mantorok1** [comment]
Thanks for that. The screenshot helps a lot.
Did the volume up/down side buttons work with the previous version of the plugin. You can re-install that version to test it. Remember to restart homebridge after installing another version. 
I'm not sure what else to try for the mute issue (when using that speaker icon in the top left)
The power icon issue is interesting. There is no remote button that corresponds to it so I'm surprised it does anything.

**Comment by mantorok1** [comment]
Stale
