### ISSUE TITLE
NFR - HomeKit receive HomeBridge Edited/Longer Names, rather than Omni device short names...

### ISSUE THREAD

**Issue by kristiandg** [mantorok1/homebridge-omnilink-platform#34]
**Is your feature request related to a problem? Please describe:**
No, more an annoyance.

**Describe the solution you'd like:**
HAI Omni devices internally have a very short character limit for their native device description, which usually requires shortening the device names to something so short, you can't really identify where something is (for example, you only have enough room to put "TrackLights", so you likely will have multiple of these in a setup). Since there's no direct indication of the zone or UPB unit number when you get device details (either in HomeBridge or HomeKit), it would be great if the device names extended to HomeKit were the more full descriptions you've saved in HomeBridge. This would mean that you'd only have to do that renaming once (on HomeBridge), and then it would be picked up automatically in HomeKit.  Right now, even if I give something a descriptive name in HomeBridge (such as "Living Room Track Lights"), all that's extended to HomeKit is what's programmed in Omni ("TrackLts"). 

Obviously HomeBridge adopts the native device name from Omni when first onboarded, but if I then edit that name to something longer and more descriptive (to compensate for the Omni's lack of longer label support), that should be what's shown in HomeKit.

**Describe alternatives you've considered:**
None, as what I have to do now is put longer labels both in HomeBridge and HomeKit independently (and manually).

**Additional context:**
None

**Comment by mantorok1** [comment]
So just to confirm you'd like the HomeKit accessories that are created by the plugin to be initially named something like:
```
{object type} {object id} {object name}
```
For example:
```
Unit 4 TrackLts
```
Is that correct?

**Comment by kristiandg** [comment]
Just the object name please, assuming the object name is the name put on the device within HomeBridge and not the name derived from the Omni. If I go to all the trouble to name them in HomeBridge with long descriptive names, then it would be great if they inherited those names upon linkage to HomeKit. Equally, when viewing the accessory in HomeBridge (like the device details), it would be helpful if you could see the actual zone/unit number so they were easier to initially identify to then put those friendly names on, but the structure of HomeBridge might not allow for that. Thanks. Kristian GuntzelmanOn Feb 12, 2024, at 12:13 AM, mantorok1 ***@***.***> wrote:﻿
So just to confirm you'd like the HomeKit accessories that are created by the plugin to be initially named something like:
{object type} {object id} {object name}

For example:
Unit 4 TrackLts

Is that correct?

**Comment by mantorok1** [comment]
So when you rename an accessory in the iOS Home app you want to see that in the equivalent accessory in Homebridge UI Accessories page. And vice versa. Is that correct?
This seems to be a known limitation of Homebridge: https://developers.homebridge.io/homebridge/#limitations

**Comment by kristiandg** [comment]
Actually I was thinking the reverse. I was hoping to be able to name everything with longer “friendly names” within HomeBridge, and then when it’s associated to HomeKit, the names that appear there are already the desired names (this is especially helpful when you sell a house, the friendly names would be maintained in the new HomeKit setup. Kristian GuntzelmanSent from my mobile device...On Feb 17, 2024, at 2:57 PM, mantorok1 ***@***.***> wrote:﻿
So when you rename an accessory in the iOS Home app you want to see that in the equivalent accessory in Homebridge UI Accessories page. And vice versa. Is that correct?
This seems to be a known limitation of Homebridge: https://developers.homebridge.io/homebridge/#limitations

**Comment by mantorok1** [comment]
Based on the wording of that limitation:

> Once an accessory has been added to the Home app, changing its name via Homebridge won't be automatically reflected in iOS. You must change it via the Home app as well.

It sounds like you should be able to rename the accessory in Homebridge BEFORE adding it to the Home app. Then when you do add it the new name should show in HomeKit.

Have you tried that? You'll need to completely remove Homebridge (or the child bridge for the plugin if you are using that) from HomeKit. You may even need to give it a new username so it thinks it's a brand new platform.

**Comment by kristiandg** [comment]
Right, I agree with that aspect. The idea is you name it in HomeBridge what you want, so when added to HomeKit, it’s already named exactly what you want and you don’t have to edit it. This facilitates much speedier re-adding for future onboarding. I’ve had to do this at a home twice in the past 3 years due to the home being sold and Apple not having a facility to “handoff” the home to a new owner. So you have to clear the HomeKit setup and re-onboard it.  By holding the names in HomeBridge, then you wouldn’t have to rename them, simply re-onboard the bridge, and all names would remain intact.

I’m only interested in it bringing in the friendly long-names at initial onboarding. A user editing them in HomeKit, is doing so out of personal preference, but that wouldn’t necessarily be the same personal preference of the next homeowner.

-
Kristian Guntzelman

**Comment by mantorok1** [comment]
Yeah I can see the benefit of it. Are you going to try it out? I'd be curious to know if it works.

If it doesn't I would raise an issue with in the Homebridge repo. I don't believe the plugin has any control over this behaviour.

**Comment by kristiandg** [comment]
I guess so. I didn’t know if that was an element you could control with this plugin or not. Now that I know it’s more on the HomeBridge side, I probably will. Kristian GuntzelmanSent from my mobile device...On Feb 17, 2024, at 8:29 PM, mantorok1 ***@***.***> wrote:﻿
Yeah I can see the benefit of it. Are you going to try it out? I'd be curious to know if it works.
If it doesn't I would raise an issue with in the Homebridge repo. I don't believe the plugin has any control over this behaviour.

**Comment by mantorok1** [comment]
Stale
