### ISSUE TITLE
omnilink plugin keeps crashing

### ISSUE THREAD

**Issue by omniuser444** [mantorok1/homebridge-omnilink-platform#39]
**Describe The Bug:**
the omnilink plugin for hoobs keeps crashing

**To Reproduce:**
every couple of days I notice the problem

**Expected behavior:**

**Logs:**
] Audio Zones found: 0
5/8/2024, 10:46:19 AM [Omni] MQTT: No broker host defined
5/10/2024, 6:23:46 PM Error: send ENETUNREACH 224.0.0.251:5353
    at doSend (dgram.js:692:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:430:12)
    at afterDns (dgram.js:638:5)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
5/10/2024, 6:23:46 PM Got SIGTERM, shutting down Bridge...
5/10/2024, 6:23:47 PM [Omni] TCP Connection: Closed
5/10/2024, 6:23:47 PM [Omni] TCP Connection: Closed
```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:  1.5.16
* **Homebridge Version**:  HOOBS Core
Version 3.3.5 (Docker)

* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**: 
docker

**Comment by mantorok1** [comment]
Hi @omniuser444,
I don't know much about HOOBS but the above error typically occurs when a Node.js application tries to send a UDP packet to a multicast address, but the network configuration prevents communication with that address. You may want to check your network settings or firewall rules to ensure that multicast communication is allowed. Additionally, make sure that the address and port being used are correct.

The address 224.0.0.251 is a reserved multicast address commonly used for mDNS (Multicast DNS) service, and port 5353 is the standard port for mDNS.

The error does not seem to be related to the OmniLink plugin as it only uses TCP, not UDP (i.e. the dgram.js library). It seems like the error might be from HOOBS itself.

Have you tried using the plugin in Homebridge directly which is the recommended way.

**Comment by omniuser444** [comment]
Ok thanks
Sent from my iPhone

On May 11, 2024, at 4:37 PM, mantorok1 ***@***.***> wrote:

﻿
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Hi @omniuser444<https://github.com/omniuser444>,
I don't know much about HOOBS but the above error typically occurs when a Node.js application tries to send a UDP packet to a multicast address, but the network configuration prevents communication with that address. You may want to check your network settings or firewall rules to ensure that multicast communication is allowed. Additionally, make sure that the address and port being used are correct.

The address 224.0.0.251 is a reserved multicast address commonly used for mDNS (Multicast DNS) service, and port 5353 is the standard port for mDNS.

The error does not seem to be related to the OmniLink plugin as it only uses TCP, not UDP (i.e. the dgram.js library). It seems like the error might be from HOOBS itself.

Have you tried using the plugin in Homebridge directly which is the recommended way.
