### ISSUE TITLE
Homebridge log shows thermostat temperature in Celsius even though Homebridge is set to Fahrenheit

### ISSUE THREAD

**Issue by Tesla-P100FX** [mantorok1/homebridge-omnilink-platform#6]
Love the plug in.  Just wondering in the log for my Homebridge it shows my thermostats in Celsius even though I have it set Fahrenheit.   Is there a way to change that.  A specific config setting for your plug in?

**Comment by mantorok1** [comment]
Hi @Tesla-P100FX,

Can you give me an example of the specific log message(s) you're referring to and I'll see what I can do.

Internally Homebridge only uses Celsius when setting or getting temperatures. iOS will then convert it to/from Fahrenheit if that's the Temperature Unit you've set in your "Language & Region" settings. So the Thermostat accessory in the Home app should display the temperature in Fahrenheit, is that correct?

**Comment by mantorok1** [comment]
@Tesla-P100FX, I think I found the log message you're referring to. It looks like this:
```
ThermostatName: temperature; mode
```
For example:
```
Kitchen: 21.5; Heat
```
This one I can change to display either C or F depending on how your Omni controller's Temperature format is set.
So, in your case, the above example would become:
```
Kitchen: 70.7F; Heat
```
Let me know if this is the what you had in mind.

**Comment by mantorok1** [comment]
The latest version of the plugin (1.4.1) should fix this issue where the log message is not displaying internal values for Homebridge/HomeKit.
