### ISSUE TITLE
Read Handler Slow to respond

### ISSUE THREAD

**Issue by Tesla-P100FX** [mantorok1/homebridge-omnilink-platform#7]
**Describe Your Problem:**
Read Handler Slow to respond , is there a way to set the system to wait longer for this so it does not generate this message to the log file. 

**Logs:**

```
/20/2021, 1:39:07 PM [HOOBS 0160@On] The read handler for the characteristic 'On' on the accessory 'BasementO/S' was slow to respond!
5/20/2021, 1:39:07 PM [HOOBS 0160@On] The read handler for the characteristic 'On' on the accessory 'Kitchen Cntr' was slow to respond!
5/20/2021, 1:39:07 PM [HOOBS 0160@On] The read handler for the characteristic 'On' on the accessory 'Craft Cove' was slow to respond!
5/20/2021, 1:39:07 PM [HOOBS 0160@On] The read handler for the characteristic 'On' on the accessory 'Basem. Kitch' was slow to respond!
5/20/2021, 1:39:07 PM [HOOBS 0160@On] The read handler for the characteristic 'On' on the accessory 'Deck Chand' was slow to respond!
5/20/2021, 1:39:07 PM [HOOBS 0160@On] The read handler for the characteristic 'On' on the accessory 'Deck Sconce' was slow to respond!
5/20/2021, 1:39:07 PM [HOOBS 0160@On] The read handler for the characteristic 'On' on the accessory 'MudRoom' was slow to respond!
5/20/2021, 1:39:07 PM [HOOBS 0160@On] The read handler for the characteristic 'On' on the accessory 'KitchenCans' was slow to respond!
5/20/2021, 1:39:07 PM [HOOBS 0160@On] The read handler for the characteristic 'On' on the accessory 'O/SMainE.LT' was slow to respond!
5/20/2021, 1:39:07 PM [HOOBS 0160@On] The read handler for the characteristic 'On' on the accessory 'Entry Chands' was slow to respond!
5/20/2021, 1:39:07 PM [HOOBS 0160@On] The read handler for the characteristic 'On' on the accessory 'Livingroom' was slow to respond!
5/20/2021, 1:39:07 PM [HOOBS 0160@On] The read handler for the characteristic 'On' on the accessory 'LivingRmwest' was slow to respond!
5/20/2021, 1:39:07 PM [HOOBS 0160@On] The read handler for the characteristic 'On' on the accessory 'DiningChand.' was slow to respond!
5/20/2021, 1:39:07 PM [HOOBS 0160@On] The read handler for the characteristic 'On' on the accessory 'DiningWest' was slow to respond!
5/20/2021, 1:39:07 PM [HOOBS 0160@On] The read handler for the characteristic 'On' on the accessory 'BackDeck' was slow to respond!
5/20/2021, 1:39:07 PM [HOOBS 0160@On] The read handler for the characteristic 'On' on the accessory 'O/SN.Entry' was slow to respond!
5/20/2021, 1:39:07 PM [HOOBS 0160@On] The read handler for the characteristic 'On' on the accessory 'Deck chandel' was slow to respond!
5/20/2021, 1:39:07 PM [HOOBS 0160@Current Temperature] The read handler for the characteristic 'Current Temperature' on the accessory 'Thermostats' was slow to respond!
5/20/2021, 1:39:07 PM [HOOBS 0160@Current Temperature] The read handler for the characteristic 'Current Temperature' on the accessory 'Temp Sen. Outdr' was slow to respond!

**Plugin Config:**

```json
 {
            "platform": "OmniLinkPlatform",
            "plugin_map": {
                "plugin_name": "homebridge-omnilink-platform"
            },
            "name": "Omni",
            "port": 4369,
            "includeAreas": true,
            "includeZones": true,
            "includeBypassZones": false,
            "includeButtons": true,
            "includeUnits": true,
            "includeThermostats": false,
            "includeEmergencyAlarms": false,
            "includeAccessControls": false,
            "includeAuxiliarySensors": true,
            "setHomeToAway": false,
            "setNightToAway": false,
            "syncTime": true,
            "showHomebridgeEvents": false,
            "showOmniEvents": false,
            "showRequestResponse": false,
            "clearCache": false,
            "forceAutoDiscovery": false,
            "defaultAccessoryMappings": {
                "zone": "motion",
                "zoneFireEmergency": "smoke",
                "unit": "switch"
            },
            "sensors": [
                {
                    "zoneId": 1,
                    "sensorType": "none"
                },
                {
                    "zoneId": 2,
                    "sensorType": "none"
                },
                {
                    "zoneId": 3,
                    "sensorType": "none"
                },
                {
                    "zoneId": 4,
                    "sensorType": "none"
                },
                {
                    "zoneId": 5,
                    "sensorType": "none"
                },
                {
                    "zoneId": 6,
                    "sensorType": "none"
                },
                {
                    "zoneId": 7,
                    "sensorType": "none"
                },
                {
                    "zoneId": 8,
                    "sensorType": "contact"
                },
                {
                    "zoneId": 9,
                    "sensorType": "none"
                },
                {
                    "zoneId": 10,
                    "sensorType": "none"
                },
                {
                    "zoneId": 11,
                    "sensorType": "none"
                },
                {
                    "zoneId": 12,
                    "sensorType": "none"
                },
                {
                    "zoneId": 13,
                    "sensorType": "none"
                },
                {
                    "zoneId": 14,
                    "sensorType": "none"
                },
                {
                    "zoneId": 15,
                    "sensorType": "contact"
                },
                {
                    "zoneId": 16,
                    "sensorType": "none"
                },
                {
                    "zoneId": 17,
                    "sensorType": "none"
                },
                {
                    "zoneId": 18,
                    "sensorType": "none"
                },
                {
                    "zoneId": 19,
                    "sensorType": "none"
                },
                {
                    "zoneId": 20,
                    "sensorType": "none"
                },
                {
                    "zoneId": 21,
                    "sensorType": "none"
                },
                {
                    "zoneId": 22,
                    "sensorType": "none"
                },
                {
                    "zoneId": 23,
                    "sensorType": "none"
                },
                {
                    "zoneId": 24,
                    "sensorType": "contact"
                },
                {
                    "zoneId": 25,
                    "sensorType": "none"
                },
                {
                    "zoneId": 26,
                    "sensorType": "none"
                },
                {
                    "zoneId": 27,
                    "sensorType": "none"
                },
                {
                    "zoneId": 28,
                    "sensorType": "none"
                },
                {
                    "zoneId": 29,
                    "sensorType": "contact"
                },
                {
                    "zoneId": 30,
                    "sensorType": "none"
                },
                {
                    "zoneId": 31,
                    "sensorType": "none"
                },
                {
                    "zoneId": 32,
                    "sensorType": "contact"
                },
                {
                    "zoneId": 33,
                    "sensorType": "none"
                },
                {
                    "zoneId": 34,
                    "sensorType": "none"
                },
                {
                    "zoneId": 35,
                    "sensorType": "none"
                },
                {
                    "zoneId": 36,
                    "sensorType": "none"
                },
                {
                    "zoneId": 37,
                    "sensorType": "none"
                },
                {
                    "zoneId": 38,
                    "sensorType": "none"
                },
                {
                    "zoneId": 39,
                    "sensorType": "contact"
                },
                {
                    "zoneId": 40,
                    "sensorType": "contact"
                },
                {
                    "zoneId": 41,
                    "sensorType": "none"
                },
                {
                    "zoneId": 42,
                    "sensorType": "none"
                },
                {
                    "zoneId": 43,
                    "sensorType": "none"
                },
                {
                    "zoneId": 44,
                    "sensorType": "none"
                },
                {
                    "zoneId": 45,
                    "sensorType": "none"
                },
                {
                    "zoneId": 46,
                    "sensorType": "none"
                },
                {
                    "zoneId": 47,
                    "sensorType": "none"
                },
                {
                    "zoneId": 48,
                    "sensorType": "contact"
                },
                {
                    "zoneId": 49,
                    "sensorType": "contact"
                },
                {
                    "zoneId": 50,
                    "sensorType": "none"
                },
                {
                    "zoneId": 51,
                    "sensorType": "none"
                },
                {
                    "zoneId": 52,
                    "sensorType": "none"
                },
                {
                    "zoneId": 53,
                    "sensorType": "none"
                },
                {
                    "zoneId": 54,
                    "sensorType": "none"
                },
                {
                    "zoneId": 55,
                    "sensorType": "none"
                },
                {
                    "zoneId": 56,
                    "sensorType": "none"
                },
                {
                    "zoneId": 57,
                    "sensorType": "none"
                },
                {
                    "zoneId": 58,
                    "sensorType": "none"
                },
                {
                    "zoneId": 59,
                    "sensorType": "none"
                },
                {
                    "zoneId": 60,
                    "sensorType": "none"
                },
                {
                    "zoneId": 61,
                    "sensorType": "none"
                },
                {
                    "zoneId": 62,
                    "sensorType": "none"
                },
                {
                    "zoneId": 63,
                    "sensorType": "none"
                },
                {
                    "zoneId": 64,
                    "sensorType": "none"
                },
                {
                    "zoneId": 65,
                    "sensorType": "none"
                },
                {
                    "zoneId": 66,
                    "sensorType": "none"
                },
                {
                    "zoneId": 67,
                    "sensorType": "none"
                },
                {
                    "zoneId": 68,
                    "sensorType": "none"
                },
                {
                    "zoneId": 69,
                    "sensorType": "none"
                },
                {
                    "zoneId": 70,
                    "sensorType": "none"
                },
                {
                    "zoneId": 71,
                    "sensorType": "none"
                },
                {
                    "zoneId": 72,
                    "sensorType": "none"
                },
                {
                    "zoneId": 73,
                    "sensorType": "none"
                },
                {
                    "zoneId": 74,
                    "sensorType": "none"
                },
                {
                    "zoneId": 75,
                    "sensorType": "none"
                },
                {
                    "zoneId": 76,
                    "sensorType": "none"
                },
                {
                    "zoneId": 77,
                    "sensorType": "none"
                },
                {
                    "zoneId": 78,
                    "sensorType": "none"
                },
                {
                    "zoneId": 79,
                    "sensorType": "none"
                },
                {
                    "zoneId": 80,
                    "sensorType": "none"
                },
                {
                    "zoneId": 81,
                    "sensorType": "none"
                },
                {
                    "zoneId": 82,
                    "sensorType": "none"
                },
                {
                    "zoneId": 83,
                    "sensorType": "none"
                },
                {
                    "zoneId": 84,
                    "sensorType": "none"
                },
                {
                    "zoneId": 85,
                    "sensorType": "none"
                },
                {
                    "zoneId": 86,
                    "sensorType": "none"
                },
                {
                    "zoneId": 87,
                    "sensorType": "none"
                },
                {
                    "zoneId": 88,
                    "sensorType": "none"
                },
                {
                    "zoneId": 89,
                    "sensorType": "none"
                },
                {
                    "zoneId": 90,
                    "sensorType": "none"
                }
            ],
            "pushover": {
                "alarms": {
                    "burglary": false,
                    "fire": false,
                    "gas": false,
                    "auxiliary": false,
                    "freeze": false,
                    "water": false,
                    "duress": false,
                    "temperature": false
                },
                "troubles": {
                    "freeze": false,
                    "batterylow": false,
                    "acpower": false,
                    "phoneline": false,
                    "digitalcommunicator": false,
                    "fuse": false
                }
            },
            "mqtt": {
                "showMqttEvents": false

**Screenshots:**
<!-- If applicable, add screenshots to help explain your problem. -->

**Environment:**

* **Plugin Version**:
**1.4.1**

* **Homebridge Version**: <!-- homebridge -V --> HOOBS 3.3.5
* **Node.js Version**:  
**14.15.1**
* **NPM Version**: <!-- npm -v -->
* **Operating System**: <!-- Raspbian / Ubuntu / Debian / Windows / macOS / Docker / hb-service -->
**Raspbian**
<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by mantorok1** [comment]
Hi @Tesla-P100FX,
Do you see these log messages every time you restart Homebridge?
Has it only started since you upgraded to 1.4.1?
Can you supply more of the logs. I'd like to see all the messages from the point that Homebridge is started to when you see the first message about the "read handler"

**Comment by Tesla-P100FX** [comment]
> Hi @Tesla-P100FX,
> 
> Do you see these log messages every time you restart Homebridge?
> 
> Has it only started since you upgraded to 1.4.1?
> 
> Can you supply more of the logs. I'd like to see all the messages from the point that Homebridge is started to when you see the first message about the "read handler"

It's not always associated with starting the service.  It happens at random times.  It has done it since my first install not 1.4.1.   I will send a complete log tomorrow.   Have a nice evening 😷

**Comment by Tesla-P100FX** [comment]
Here is the complete startup log.  It did not happen in this window of time  but suspect it might later.

5/21/2021, 9:16:03 AM Initializing HAP-NodeJS v0.9.3...
5/21/2021, 9:16:04 AM Loaded plugin 'homebridge-myq'
5/21/2021, 9:16:05 AM [5/21/2021, 9:16:04 AM] Registering platform 'homebridge-myq.myQ'
5/21/2021, 9:16:05 AM Loaded plugin 'homebridge-omnilink-platform'
5/21/2021, 9:16:05 AM [5/21/2021, 9:16:05 AM] Registering platform 'homebridge-omnilink-platform.OmniLinkPlatform'
5/21/2021, 9:16:05 AM [5/21/2021, 9:16:05 AM] The plugin "homebridge-platform-wemo" requires Node.js version of ^14.16.1 which does not satisfy the current Node.js version of v14.15.1. You may need to upgrade your installation of Node.js - see https://git.io/JTKEF
5/21/2021, 9:16:05 AM Loaded plugin 'homebridge-platform-wemo'
5/21/2021, 9:16:05 AM Loading 3 platforms...
5/21/2021, 9:16:05 AM [5/21/2021, 9:16:05 AM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
5/21/2021, 9:16:05 AM [Omni] Initializing OmniLinkPlatform platform...
5/21/2021, 9:16:05 AM [Wemo] Initializing BelkinWeMo platform...
5/21/2021, 9:16:05 AM [myQ] Initializing myQ platform...
5/21/2021, 9:16:05 AM [Wemo] [v3.0.9] initialised. Setting up device discovery.
5/21/2021, 9:16:06 AM Preparing Advertiser for 'HOOBS 0160' using bonjour-hap backend!
5/21/2021, 9:16:06 AM Starting to advertise 'HOOBS 0160' using bonjour-hap backend!
5/21/2021, 9:16:06 AM Bridge is running on port 51826.
5/21/2021, 9:16:06 AM [Omni] TCP Connection: Open
5/21/2021, 9:16:06 AM [Wemo] [Third Floor Office II] initialised with s/n 2299A029N03133 and ip/port 10.0.0.52:49153
5/21/2021, 9:16:06 AM [Wemo] [Third Floor Office II] current state [off].
5/21/2021, 9:16:06 AM [Wemo] [Rear Deck Exterior Light] initialised with s/n 2299A029N031B6 and ip/port 10.0.0.170:49153
5/21/2021, 9:16:06 AM [Wemo] [Rear Deck Exterior Light] current state [off].
5/21/2021, 9:16:06 AM [Omni] Configure securitysystem: Area 1
5/21/2021, 9:16:06 AM [Omni] Configure contactsensor: Front Door
5/21/2021, 9:16:06 AM [Omni] Configure contactsensor: Dining Frnch Dr
5/21/2021, 9:16:06 AM [Omni] Configure contactsensor: Kitchen Door
5/21/2021, 9:16:06 AM [Omni] Configure contactsensor: Garage House Dr
5/21/2021, 9:16:06 AM [Omni] Configure contactsensor: Recroom Door
5/21/2021, 9:16:06 AM [Omni] Configure contactsensor: N Lower Gate
5/21/2021, 9:16:06 AM [Omni] Configure contactsensor: S Lower Gate
5/21/2021, 9:16:06 AM [Omni] Configure contactsensor: Mstr Br Frnch l
5/21/2021, 9:16:06 AM [Omni] Configure contactsensor: Mstr Br Frnch R
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: KitchenDesk
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: KitchenTable
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: Stairway
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: Mattews room
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: Laurens Room
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: 2nd Flr.Hall
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: Master Hall
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: MasterCloset
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: Master Deck
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: UpperFloor
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: Master Bed
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: O/SGarage
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: Kitchen Bath
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: Garage
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: Basement Ctr
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: BasementO/S
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: Kitchen Cntr
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: Craft Cove
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: Basem. Kitch
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: Deck Chand
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: Deck Sconce
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: MudRoom
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: KitchenCans
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: O/SMainE.LT
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: Entry Chands
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: Livingroom
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: LivingRmwest
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: DiningChand.
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: DiningWest
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: BackDeck
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: O/SN.Entry
5/21/2021, 9:16:06 AM [Omni] Configure unitswitch: Deck chandel
5/21/2021, 9:16:06 AM [Omni] Configure temperaturesensor: Thermostats
5/21/2021, 9:16:07 AM [Omni] Configure temperaturesensor: Temp Sen. Outdr
5/21/2021, 9:16:07 AM [Omni] Read config from cache [/home/hoobs/.hoobs/etc/OmnilinkPlatform/Omni.json]
5/21/2021, 9:16:07 AM [Wemo] [Dining Room Cans] initialised with s/n ************and ip/port 10.0.0.102:49153
5/21/2021, 9:16:07 AM [Wemo] [Dining Room Cans] current state [off].
5/21/2021, 9:16:07 AM [Wemo] [Wemo Light Switch] initialised with s/n *********** and ip/port 10.0.0.56:49153
5/21/2021, 9:16:07 AM [Wemo] [Wemo Light Switch] current state [off].
5/21/2021, 9:16:07 AM [Wemo] ✓ Setup complete. Have time to give this plugin a review? http://bit.ly/hb-wemo-review
5/21/2021, 9:16:09 AM [myQ] myQ API: Successfully connected to the myQ API.
5/21/2021, 9:16:09 AM [myQ] myQ API: Discovered device family garagedoor: Garage Door (serial number: ************gateway: GW23001A4270).
5/21/2021, 9:16:09 AM [myQ] myQ API: Discovered device family gateway: Hub [Chamberlain Smart Garage Hub] (serial number: GW23001A4270).
5/21/2021, 9:16:09 AM [myQ] Garage Door: Door position sensor detected. Enabling battery status support.
5/21/2021, 9:16:20 AM [Omni] Found: OmniPro II [Firmware version: 3.11c]
5/21/2021, 9:16:20 AM [Omni] Areas found: 1
5/21/2021, 9:16:20 AM [Omni]     1: Area 1
5/21/2021, 9:16:20 AM [Omni] Zones found: 78
5/21/2021, 9:16:20 AM [Omni]     1: Smoke Detectors   [Fire]
5/21/2021, 9:16:20 AM [Omni]     2: Heat Furnace Rm   [Fire]
5/21/2021, 9:16:20 AM [Omni]     3: Heat Kitchen      [Fire]
5/21/2021, 9:16:20 AM [Omni]     4: Heat Laundry Rm   [Fire]
5/21/2021, 9:16:20 AM [Omni]     8: Front Door        [DoubleEntryDelay]
5/21/2021, 9:16:20 AM [Omni]    11: Livng S L Frnch   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    12: Livng S R Frnch   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    13: Liv Rm Door L     [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    14: Liv Rm Door R     [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    15: Dining Frnch Dr   [DoubleEntryDelay]
5/21/2021, 9:16:20 AM [Omni]    16: Thermostats       [Temperature]
5/21/2021, 9:16:20 AM [Omni]    17: Dining Rm Win L   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    18: Dining Rm Win R   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    20: Kitchen Win W C   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    21: Kitchen Win W R   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    22: Kitchen Win N L   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    23: Kitchen Win N R   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    24: Kitchen Door      [EntryExit]
5/21/2021, 9:16:20 AM [Omni]    25: Kitchen Ent Win   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    26: MainFl Bath Win   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    28: Lower Stair Win   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    29: Garage House Dr   [DoubleEntryDelay]
5/21/2021, 9:16:20 AM [Omni]    30: Recroom Win M     [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    31: Recroom Win R     [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    32: Recroom Door      [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    33: Furnace Gar Dr    [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    34: Front Win L       [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    35: Front Win R       [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    37: Furnace Win R     [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    39: N Lower Gate      [Auxiliary]
5/21/2021, 9:16:20 AM [Omni]    40: S Lower Gate      [Auxiliary]
5/21/2021, 9:16:20 AM [Omni]    41: Laundry Top Win   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    42: Mstr Shower Win   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    43: Mstr Toilet Win   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    44: Mstr Br NE UWin   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    45: Mstr Br NE LWin   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    46: Mstr Br SE UWin   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    47: Mstr Br SE LWin   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    48: Mstr Br Frnch l   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    49: Mstr Br Frnch R   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    50: MstrBr W LowWin   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    51: MstrBr W UpWinL   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    52: MstrBr W UpWinR   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    53: 3rd Stair Win L   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    54: 3rd Stair Win R   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    55: Office Window E   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    56: Office W Win L    [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    58: Office W Win R    [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    59: Office N Win      [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    60: Office E Win L    [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    61: Office E Win R    [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    62: Sitting Win L     [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    63: Sitting Win R     [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    64: Mstr Closet Win   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    65: Lauren S Window   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    66: Lauren W Win L    [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    67: Lauren W Win M    [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    68: Lauren W Win R    [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    69: Lauren Bath Win   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    71: Mathew W Win      [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    72: Mathew N Win      [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    73: Mathew E Win L    [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    74: Mathew E Win R    [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    75: Mstr W Low Win    [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    76: Laundry Low Win   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    77: Mstr Toilet Win   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    78: Lauren WUL Win    [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    79: Lauren WUM Win    [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    80: Lauren WUR Win    [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    81: Lauren Bath Win   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    83: Lauren Br S Win   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    84: Liv Rm SUL Win    [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    85: Liv Rm SLL Win    [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    86: Mstr Br ME UWin   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    87: Mstr Br ME LWin   [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    88: Temp Sen. Outdr   [OutdoorTemperature]
5/21/2021, 9:16:20 AM [Omni]    89: Liv Rm SUR Win    [Perimeter]
5/21/2021, 9:16:20 AM [Omni]    90: Liv Rm SLR Win    [Perimeter]
5/21/2021, 9:16:20 AM [Omni] Units found: 32
5/21/2021, 9:16:20 AM [Omni]     9: KitchenDesk       [Compose]
5/21/2021, 9:16:20 AM [Omni]    10: KitchenTable      [Compose]
5/21/2021, 9:16:20 AM [Omni]    13: Stairway          [Compose]
5/21/2021, 9:16:20 AM [Omni]    14: Mattews room      [Compose]
5/21/2021, 9:16:20 AM [Omni]    15: Laurens Room      [Compose]
5/21/2021, 9:16:20 AM [Omni]    16: 2nd Flr.Hall      [Compose]
5/21/2021, 9:16:20 AM [Omni]    17: Master Hall       [Compose]
5/21/2021, 9:16:20 AM [Omni]    18: MasterCloset      [Compose]
5/21/2021, 9:16:20 AM [Omni]    19: Master Deck       [Compose]
5/21/2021, 9:16:20 AM [Omni]    20: UpperFloor        [Compose]
5/21/2021, 9:16:20 AM [Omni]    21: Master Bed        [Compose]
5/21/2021, 9:16:20 AM [Omni]    22: O/SGarage         [Compose]
5/21/2021, 9:16:20 AM [Omni]    25: Kitchen Bath      [Compose]
5/21/2021, 9:16:20 AM [Omni]    26: Garage            [Compose]
5/21/2021, 9:16:20 AM [Omni]    27: Basement Ctr      [Compose]
5/21/2021, 9:16:20 AM [Omni]    28: BasementO/S       [Compose]
5/21/2021, 9:16:20 AM [Omni]    29: Kitchen Cntr      [Compose]
5/21/2021, 9:16:20 AM [Omni]    30: Craft Cove        [Compose]
5/21/2021, 9:16:20 AM [Omni]    31: Basem. Kitch      [Compose]
5/21/2021, 9:16:20 AM [Omni]    33: Deck Chand        [Compose]
5/21/2021, 9:16:20 AM [Omni]    34: Deck Sconce       [Compose]
5/21/2021, 9:16:20 AM [Omni]    50: MudRoom           [HLCLoad]
5/21/2021, 9:16:20 AM [Omni]    51: KitchenCans       [HLCLoad]
5/21/2021, 9:16:20 AM [Omni]    52: O/SMainE.LT       [HLCLoad]
5/21/2021, 9:16:20 AM [Omni]    53: Entry Chands      [HLCLoad]
5/21/2021, 9:16:20 AM [Omni]    54: Livingroom        [HLCLoad]
5/21/2021, 9:16:20 AM [Omni]    55: LivingRmwest      [HLCLoad]
5/21/2021, 9:16:20 AM [Omni]    58: DiningChand.      [HLCLoad]
5/21/2021, 9:16:20 AM [Omni]    59: DiningWest        [HLCLoad]
5/21/2021, 9:16:20 AM [Omni]    60: BackDeck          [HLCLoad]
5/21/2021, 9:16:20 AM [Omni]    61: O/SN.Entry        [HLCLoad]
5/21/2021, 9:16:20 AM [Omni]   225: Deck chandel      [UPB]
5/21/2021, 9:16:20 AM [Omni] Buttons found: 0
5/21/2021, 9:16:20 AM [Omni] Thermostats found: 9
5/21/2021, 9:16:20 AM [Omni]     1: Front Door
5/21/2021, 9:16:20 AM [Omni]     2: Master Bath
5/21/2021, 9:16:20 AM [Omni]     3: Lauren Bedrm
5/21/2021, 9:16:20 AM [Omni]     4: Mathew's 
5/21/2021, 9:16:20 AM [Omni]     5: Master Bedrm
5/21/2021, 9:16:20 AM [Omni]     6: Rich's Offic
5/21/2021, 9:16:20 AM [Omni]     7: Dining Room
5/21/2021, 9:16:20 AM [Omni]     8: Kitchen Hall
5/21/2021, 9:16:20 AM [Omni]     9: Lauren Bath
5/21/2021, 9:16:20 AM [Omni] Access Controls found: 0
5/21/2021, 9:16:20 AM [Omni] Auxiliary Sensors found: 2
5/21/2021, 9:16:20 AM [Omni]    16: Thermostats
5/21/2021, 9:16:20 AM [Omni]    88: Temp Sen. Outdr
5/21/2021, 9:16:20 AM [Omni] MQTT: No broker host defined

**Comment by mantorok1** [comment]
One thing you can check is the CPU usage of your RPi when you notice these warnings occur. In my own case (a QNAP NAS) I found I was getting warnings from Homebridge when the CPU was running high (90+%). This was caused by another process (not related to Homebridge) which I disabled and have not seen the warnings since. The CPU is normally running at around 10%

You are running a few plugins I noticed so maybe the RPi hardware is struggling. Other than Homebridge is anything else running on your RPi?

You could also try running the plugin in a [Child Bridge](https://github.com/homebridge/homebridge/wiki/Child-Bridges) (which is what I do). Just be aware that if you do this all the HomeKit accessories for the plugin will be removed and then re-added so you may need set up any scenes and automations again.

**Comment by Tesla-P100FX** [comment]
Sorry I have not followed up.  CPU usage is always super low , do it's not that.   I'll debug tomorrow between meetings

**Comment by mantorok1** [comment]
No worries. I think the issue may be that you have a quite a number of units, zones etc.  When HomeKit requests updates for the various accessories the plugin will fetch the current status for each one (one at a time) from the Omni controller. It could be this that's taking too long to respond.
I'm working on a way to reduce these calls to the Omni controller to hopefully help with this issue.
If you do find anything else with your own debugging please let me know.

**Comment by Tesla-P100FX** [comment]
Thanks for working on an update to solve this.  I will update as soon as it shows up in the Hoobs plug in directory

**Comment by mantorok1** [comment]
I just released a new version of the plugin (1.4.3) which may fix the issue. Give it a go and let me know what happens.

**Comment by Tesla-P100FX** [comment]
Thanks I will as soon as I see it as a package  in Hoobs

**Comment by mantorok1** [comment]
Hi @Tesla-P100FX, did you upgrade the plugin? Has it helped at all?

**Comment by Tesla-P100FX** [comment]
Yes thank you!   I thought I would wait a couple of days to see if it had any errors.  I installed on 5/29 and no errors since then:-)

Thank you!!

**Comment by mantorok1** [comment]
That's great news. I'll leave this issue option for now but if I haven't heard anything further from you by next weekend I'll assume its ok and close it
